# Generated by Django 3.2.20 on 2023-07-24 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Companie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('Address1', models.CharField(max_length=100)),
                ('Address2', models.CharField(max_length=100)),
                ('Address3', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Website', models.CharField(max_length=100)),
                ('Logo', models.ImageField(upload_to='')),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry_source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enquirysourcename', models.CharField(max_length=100)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Follow_up_statu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Followupstatusname', models.CharField(max_length=150)),
                ('Followupstatus', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Master_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Value', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qualificationname', models.CharField(max_length=100)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Syllabus', models.CharField(max_length=100)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.CharField(max_length=300, unique=True)),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETTINGS.state')),
            ],
            options={
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=100)),
                ('Course_code', models.CharField(max_length=100)),
                ('Active', models.BooleanField(default=True)),
                ('Trainers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch', models.CharField(max_length=300)),
                ('Branchcode', models.CharField(default='Branchcode', max_length=200)),
                ('Address', models.CharField(blank=True, max_length=400)),
                ('Street', models.CharField(blank=True, max_length=250)),
                ('Pincode', models.CharField(blank=True, max_length=250)),
                ('Mobile', models.CharField(max_length=200)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETTINGS.state')),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_date', models.DateField()),
                ('End_date', models.TimeField()),
                ('Closed', models.BooleanField()),
                ('Active', models.BooleanField(default=True)),
                ('Trainers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETTINGS.course')),
            ],
        ),
    ]
