# Generated by Django 3.2.20 on 2023-07-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SETTINGS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
