# Generated by Django 3.2.20 on 2023-07-24 09:53

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('SETTINGS', '0002_auto_20230724_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name_plural': 'Districts'},
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch', models.CharField(max_length=300)),
                ('Branchcode', models.CharField(default='Branchcode', max_length=200)),
                ('Address', models.CharField(blank=True, max_length=400)),
                ('Street', models.CharField(blank=True, max_length=250)),
                ('Pincode', models.CharField(blank=True, max_length=250)),
                ('Mobile', models.CharField(max_length=200)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('District', smart_selects.db_fields.ChainedForeignKey(chained_field='State', chained_model_field='State', on_delete=django.db.models.deletion.CASCADE, to='SETTINGS.district', verbose_name='District')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETTINGS.state')),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
    ]
