# Generated by Django 3.2.20 on 2023-07-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SETTINGS', '0003_auto_20230724_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='State',
            new_name='state',
        ),
    ]
