# Generated by Django 3.2.20 on 2023-07-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SETTINGS', '0005_auto_20230724_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='state',
            new_name='State',
        ),
        migrations.RemoveField(
            model_name='companie',
            name='Active',
        ),
        migrations.RemoveField(
            model_name='enquiry_source',
            name='Active',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='Active',
        ),
        migrations.RemoveField(
            model_name='state',
            name='Active',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='Active',
        ),
    ]
