# Generated by Django 3.2.20 on 2023-07-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SETTINGS', '0006_auto_20230724_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='Branchcode',
            field=models.CharField(default='', max_length=200),
        ),
    ]
