# Generated by Django 3.2.20 on 2023-07-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SETTINGS', '0007_alter_branch_branchcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companie',
            new_name='Company',
        ),
        migrations.RenameModel(
            old_name='Follow_up_statu',
            new_name='Follow_up_status',
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'j.  Batch'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'd.  Branch'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'a.  Company'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'i.  Course'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name_plural': 'c.  District'},
        ),
        migrations.AlterModelOptions(
            name='enquiry_source',
            options={'verbose_name_plural': 'e.  Enquiry_source'},
        ),
        migrations.AlterModelOptions(
            name='follow_up_status',
            options={'verbose_name_plural': 'f.  Follow_up_status'},
        ),
        migrations.AlterModelOptions(
            name='master_data',
            options={'verbose_name_plural': 'k.  Master_data'},
        ),
        migrations.AlterModelOptions(
            name='qualification',
            options={'verbose_name_plural': 'g.  Qualification'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': 'b.  State'},
        ),
        migrations.AlterModelOptions(
            name='syllabus',
            options={'verbose_name_plural': 'h.  Syllabus'},
        ),
    ]
